### PR TITLE
#1 photoupload

### PR DESCRIPTION
**Pull request by zmchristensen**
Implement v1 of the iOS app that allows users to log in with Facebook and page through their camera sites. Users can also create new camera sites based on their current location, as well as as photos to existing sites.

### CODE REVIEW

**Comment by icotting** [comment]
@zmchristensen I took a couple of photos and it always uploaded the same (first) photo. I also think the icons for add, take picture, and log off need to be bigger.

**Comment by zmchristensen** [comment]
Fixed the cover photo issue in icotting/Phocalstream#200.

**Comment by zmchristensen** [comment]
Those icons were initially set up as Bar Button items, which have a fixed size, right? Do you want me to implement them as UIButtons with images so we can adjust the size?

**Comment by icotting** [comment]
The images are standard bar button size. They just seem to be much smaller on my iPhone 5S than normal bar buttons items.

**Comment by icotting** [comment]
With the new server update it seems to be behaving as it did. Looking into it more, the pictures I am taking are showing up in the wrong site. I launch the app, don't switch sites, tap the camera button, take a picture and the image ends up in the second site when I would expect it in the first.

**Comment by icotting** [comment]
Also, so kind of indicator that something has happened would be good.  I would recommend: 

Tap 'Use Image' 
Some indicator that something is happening takes place with the upload being threaded so that it doesn't hijack the entire UI
On successful update, user is notified
Cover image is rerendered so that it is the image that was just taken
If upload fails, user should be notified.

**Comment by zmchristensen** [comment]
@icotting: yes, those images do appear to be rending smaller. Not sure why that is. Maybe the size requirements for bar button icons changed since those were created? 

Also, the 3x size for the camera icon is a different image than the other two. 
screenshot 2015-09-23 17 23 41

Should we update that, or just use the default ios camera icon?
simulator screen shot sep 23 2015 5 26 57 pm

**Comment by icotting** [comment]
@zmchristensen I updated the images to correct sizes. I like the way ti looks having them in the nav bar like that. Let's keep that but with the new images I just committed.

**Pull request merged**
